server:
  port: 8087


#配置一个用户可以操作的数据接口
person:
  age: 30
  name: zhengsan@qq.com
  sex: true
  list:
    - aaa
    - ddd
    - ccc
  map:
    f: fff
    g: ggg

  cat:
    age: 6
    name: qute









